### ISSUE TITLE
xfce4 file manager crashes when entering /proc

### ISSUE THREAD

**Issue by olleharstedt** [DragonFlyBSD/DPorts#140]
Release 4.
Any more information needed?

**Comment by jrmarino** [comment]
This is mainly for build issues.  You're talking about a run-time issue which I personally don't have time to investigate (we have 22,000 ports!).  If you have a patch, that's a different story.  Otherwise I think you'll have to run this down yourself or get some help.

Iow - it's not even clear from this if the problem is with xfce or dragonfly.

**Comment by jrmarino** [comment]
If this is still a problem:
1) open a ticket at bugs.dragonflybsd.org
2) if the resulting investigate determines it's a port problem -and- a patch is provided, please reopen this issue and provide a link to the fix.
