### ISSUE TITLE
Kamailio (FreeBSD Ports) not compiling - clang issue

### ISSUE THREAD

**Issue by blackknightx2** [DragonFlyBSD/DPorts#151]
I am trying to compile kamailio, using the FreeBSD Ports-File. I just copied the FreeBSD-Ports directory and  set it under /usr/dports/net/kamailio

make config is running but  when i try to compile everything  I get the following error.

=========================================================================
ostel# make
===>  Building for kamailio-4.2.4
cd /usr/obj/dports/net/kamailio/work/kamailio-4.2.4 && gmake
group_include="standard standard-dep postgres radius presence"
include_modules="jabber tls"
DESTDIR=/usr/obj/dports/net/kamailio/work/stage cfg
gmake[2]: Entering directory
'/s/usr-obj/dports/net/kamailio/work/kamailio-4.2.4'
clang: not found
Makefile.defs:347: Unknown compiler clang\; supported compilers: gcc,
sun cc, intel icc
target architecture <x86_64>, host architecture <x86_64>
making config...
rm -f modules.lst
gmake --no-print-directory modules.lst
saving modules list...
gmake[2]: Leaving directory
'/s/usr-obj/dports/net/kamailio/work/kamailio-4.2.4'
cd /usr/obj/dports/net/kamailio/work/kamailio-4.2.4 && gmake all
gmake[2]: Entering directory
'/s/usr-obj/dports/net/kamailio/work/kamailio-4.2.4'
CC (clang) [kamailio]           nonsip_hooks.o
clang: not found
Makefile.rules:114: recipe for target 'nonsip_hooks.o' failed
gmake[2]: *** [nonsip_hooks.o] Error 127
gmake[2]: Leaving directory
'/s/usr-obj/dports/net/kamailio/work/kamailio-4.2.4'
*** Error code 2
=============================================================================

It seems iam missing clang. I assume Dragonfly BSD is ussing gcc and 
here is my Question.

How do i modifiy the Port to make it compile under gcc ?

Thank you.

**Comment by jrmarino** [comment]
This "report" could well be considered out of scope of dports issues.
It's known not to build, which is why it is not in dports.  The fact you had to copy the port means it was destined to fail, 100% chance.  There are about 1400 ports that do not build for one reason or another.

So the report boils down to "help me fix a known broken port"

The process is really supposed to be reversed -- if you come up with the fix in the form of a patch, you submit and we get the port building.

As for the actual problem, if it's hardcoded for clang, then either a patch or the ports makefile is probably changed to make that happen.  Look at the existing patches and the makefile and figure out why clang is hardcoded, then remove that.  Also look in makefile.defs, the file that is complaining.

You have barely scratched the surface.  

(I barely have time to fix ports when then fix is known -- I simply do not have time to look at individual ports upon request when no diagnosis has been done)

**Comment by blackknightx2** [comment]
Ok understood,

I'll have a look at the Make-Files and see what i can learn ........

**Comment by jrmarino** [comment]
no patch provided so considering issue closed.
