### ISSUE TITLE
No Audio when using VLC

### ISSUE THREAD

**Issue by am-dxer** [DragonFlyBSD/DPorts#193]
Hello,
I can't play audio files when using VLC Media Player on Dragonfly bsd. I see a message in the terminal saying "core audio error: no suitable output module" and I thought maybe its related.

**Comment by jrmarino** [comment]
It might be.  I'm not sure if VLC works without pulseaudio.  Somebody needs to troubleshoot it.  I remember people talking about VLC before but I'm not sure what the current status is.

**Comment by ccrollo** [comment]
@jrmarino I know this is an old issue, and I don't have a live system handy to test this or make a patch with, but looking at VLC's Makefile, the issue seems to be with the port having both "--disable-oss" and "--disable-alsa" in the CONFIGURE_ARGS, as well as PulseAudio and sndio being the only audio options defined, but neither are being set by default either. I think what's happening for DragonFly is, with PulseAudio filtered out system-wide, VLC is compiling without the only valid output option the port is allowing. I'm not sure why FreeBSD is doing it this way (I guess they expect everyone to be using PulseAudio), but either masking out the offending configure args to allow ALSA again, or at least putting "OPTIONS_DEFAULT+=SNDIO" in this port's Makefile.DragonFly, should fix the "no suitable output module" error.

**Comment by tuxillo** [comment]
Should be fixed in https://github.com/DragonFlyBSD/DeltaPorts/commit/dd4e3973258fca47a74ba199cb14a327c22b6c3f

Tested locally, sound works okay.
