### ISSUE TITLE
What is the problem with dialog4ports ?

### ISSUE THREAD

**Issue by devosalain** [DragonFlyBSD/DPorts#241]
This is normally the first package.
But it is not even in packages & ports don't compile.

**Comment by daftaupe** [comment]
Hello,

the problem is that it was broken and none of us in the team use it.

Please read https://lists.dragonflybsd.org/pipermail/users/2023-February/428561.html
or read the new PER-PORT OPTIONS of https://man.dragonflybsd.org/?command=dsynth&section=ANY

If you really need dialog4ports you can build it using https://github.com/DragonFlyBSD/DeltaPorts/commit/7b8178e4df5f531ecc15bc13218c486c6dac624d referenced in (https://bugs.dragonflybsd.org/issues/3334)

Next time it should be shipped as a binary package.
