### ISSUE TITLE
no screens found when installed with KVM

### ISSUE THREAD

**Issue by jay763190097** [DragonFlyBSD/DPorts#243]
![image](https://user-images.githubusercontent.com/16317178/219957725-1781dbd9-d275-47c3-b667-0f137fb11455.png)
![image](https://user-images.githubusercontent.com/16317178/219957744-238e5270-ef0a-4a28-b3fb-4c6ed3e9f0b3.png)
I use the latest version: dfly-x86_64-6.4.0_REL.iso

**Comment by daftaupe** [comment]
Hi @jay763190097,

what type of gpu are you providing the vm with ?
I think you need a minimal config file for the scfb backend to work.
I didn't check but I would say something like the following in /usr/local/etc/X11/xorg.conf.d/scfb.conf
```
Section "Device"
 Identifier "Card0"
 Driver     "scfb"
EndSection
```

**Comment by krionical** [comment]
I made your suggested change as indicated as I have the same issue:

![image](https://github.com/DragonFlyBSD/DPorts/assets/20403484/225a0ed9-49fb-4bff-943e-4673d4fee11a)


It did not resolve the problem. Right now, I'm using "VGA" as the model in Qemu.

**Comment by daftaupe** [comment]
@krionical that's only part of the log file, could you please post the whole file somewhere ?

**Comment by krionical** [comment]
I had hoped to extract this file from dragonfly and get it to you in some neat text form, but it turns out that that is not a trivial matter since Qemu mounts disks in a strange way that are external when it comes to dragonflybsd. My next stop was going to be magic wormhole, but that didn't work because of various complications with rust. Hence, I am just going to send the screen shots here of the log, since that's about the easiest way to do this I can see.

![bsd1](https://github.com/DragonFlyBSD/DPorts/assets/20403484/4be2a374-cedc-45f4-86dc-4940baa42b8b)
![bsd2](https://github.com/DragonFlyBSD/DPorts/assets/20403484/a2639aed-8e5c-46b7-b8f0-14a7bb0f5c55)
![bsd3](https://github.com/DragonFlyBSD/DPorts/assets/20403484/5a28cc85-f9d8-4d75-8dd7-8d60f1c71dcd)
[
![bsd4](https://github.com/DragonFlyBSD/DPorts/assets/20403484/ec0aa3a6-3b98-4057-86c3-8005f952ffc1)
](url)

Maybe there is some advantage to this for people who come after me and can compare their own logs right here. If not, I apologize if this sucks up more bandwidth than usually appropriate.

**Comment by servizig** [comment]
I removed [this patch](https://github.com/DragonFlyBSD/DeltaPorts/blob/master/ports/x11-drivers/xf86-video-scfb/dragonfly/patch-src_scfb__driver.c) (fb.fb_type has value FBTYPE_VGA) and could start X even without config files. But screen rendered some funny colored ASCII art, I've never seen anything like this before and didn't investigate further.

**Comment by daftaupe** [comment]
@krionical sorry I didn't notice your answer at the time. Can you provide the vm configuration please, if you still have it, or if there's an easy way for me to recreate it.

@servizig interesting, but so it means that going to VESA when not in VESA mode doesn't work properly, if I understand what the patch does correctly
