### ISSUE TITLE
Rust version

### ISSUE THREAD

**Issue by michalszmidt** [DragonFlyBSD/DPorts#252]
Hi!

Thank you for DragonflyBSD :heart:

I'd like to ask why rust is tier3 on dfly? 
Would it be possible to make it tier 2 so I could fetch newest from rustup?

I ask because dfly version from repo is quite old, so I can't build many stuff.

**Comment by daftaupe** [comment]
Hi @michalszmidt

I understand that Rust is going fast but we do have the version 1.68.2 available in DPorts, which is from March 2023, so I wouldn't say "quite old", as it's not even 6 months ago.
Also 1.70 is coming soon as it's already in staged : https://github.com/DragonFlyBSD/DPorts/commit/6d9e6554cf5ad8809ffbe86649fbff6cd8287308. You can grab it and test it if you want to.

I don't know what's behind becoming tier2 instead of tier3, but here's only one person working on the port at the moment, so please keep reasonnable expectations about what is achievable and what is not. The limiting factor being usually just the number of hands doing the required job.

Anyways @tuxillo probably has better answsers than I do.

**Comment by tuxillo** [comment]
> Hi!
> 
> Thank you for DragonflyBSD ❤️
> 
> I'd like to ask why rust is tier3 on dfly? Would it be possible to make it tier 2 so I could fetch newest from rustup?
> 
> I ask because dfly version from repo is quite old, so I can't build many stuff.

I guess with the correct amount of work you can go past tier 3, we'd have to check with the Rust people after making sure we meet the requirements. It's mostly a matter of time/work.
