### ISSUE TITLE
databases/sqlite3 has little problem

### ISSUE THREAD

**Issue by tu-min** [DragonFlyBSD/DPorts#77]
make: make: don't know how to make ./libsqlite3.la. Stop

**Comment by FlorianHeigl** [comment]
===> CONFIGURE_ARGS=--enable-dynamic-extensions --enable-readline --enable-threadsafe --prefix=/usr/local 
===> CPPFLAGS=-DSQLITE_ENABLE_API_ARMOR=1 -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_FTS3_PARENTHESIS=1 -DSQLITE_ENABLE_FTS4=1 -DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 -DSQLITE_ENABLE_COLUMN_METADATA=1 -DSQLITE_SECURE_DELETE=1 -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 -DSQLITE_USE_URI=1 -DSQLITE_TEMP_STORE=1 -DSQLITE_DISABLE_FTS3_UNICODE=1
===> LDFLAGS= -pthread -Wl,-rpath=/usr/lib:/usr/local/lib -fstack-protector
===>  Building for sqlite3-3.8.8.2
make[2]: make[2]: don't know how to make ./libsqlite3.la. Stop

make[2]: stopped in /usr/ports/databases/sqlite3/work/sqlite-autoconf-3080802
*** Error code 1


of course you thought it fixed when you closed the bug :)

**Comment by jrmarino** [comment]
I'll repeat it again.
http://muscles.dragonflybsd.org/bulk/bleeding-edge-potential/latest-per-pkg/sqlite3-3.8.8.2.log

It builds in the official builders with poudriere: muscles (4.1), pkgbox64 (3.8, 4.0. 4.1).
Those are known, controlled environments and packages are produced.

You are apparently building on a live system and claiming a "bug" since it's failing.  There is not way to know what is going on in such an environment.  Unless you can reproduce this in poudriere, this can't be considered a bug.

I never "fixed" anything.  I closed the ticket because it the report could not be reproduced and still can't.   it's something specific to your system.
